language: python

python:
  - 2.7
  - 3.6
  - 3.5
  - 3.4
  - 3.3

# Use container-based infrastructure
sudo: false

install:
  - travis_retry pip install pyflakes
  - travis_retry pip install yamllint
  - travis_retry pip install demjson

script:
  - pyflakes drupal/build.sh
  - yamllint .
  - find . -name \*.json | xargs -I {} jsonlint {}

after_success:
  - travis_retry pip install pep8
  - pep8 --statistics --count drupal/build.sh

matrix:
  fast_finish: true

  allow_failures:
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 3.3

notifications:
  email: false
