project:
  name: wundertools
ansible:
  remote: git@github.com:wunderkraut/WunderMachina.git
  branch: master
  revision:
buildsh:
  enabled: true
  branch: master
  revision:
wundertools:
  branch: master
externaldrupal:
  remote:
  branch:

